### ISSUE TITLE
Bundler could not find compatible versions for gem "json":

### ISSUE THREAD

**Issue by ravindra9278** [eatabit/eatabit_rails#1]
Hi I have tried to install "eatabit_rails" gem in my existing rails app but it was showing 'JSON' version issue. I have already have updated JSON version 2.1.0 but eatabit_rails require lesser JSON version 1.8.3, Please see error:

Resolving dependencies.......
Bundler could not find compatible versions for gem "json":
  In snapshot (Gemfile.lock):
    json (= 2.1.0)

  In Gemfile:
    eatabit_rails was resolved to 0.1.1, which depends on
      json (>= 1.8.3, ~> 1.8)

**Comment by goleksiak** [comment]
We released the 0.2.1 version of the eatabit_rails gem to address this issue. https://rubygems.org/gems/eatabit_rails
